language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build --config _config_dev.yml
  - bundle exec htmlproof ./_site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
