title: Books
description: A simple example of using collections with Jekyll
permalink: /blog/:categories/:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["Rmd", ".DS_Store", "README.md", "vendor"]
excerpt_separator: <!--more-->
baseurl: /books
url: http://koheron.github.io
host_url: https://www.koheron.com
collections: 
  - books
gems:
  - jekyll-mentions

